language: go
git:
  depth: 1
go:
  - master
env:
  - GO111MODULE=on
script:
  - go get -v
  - go test -v ./... -covermode=count -coverprofile=coverage.out
after_success:
  - bash <(curl -s https://codecov.io/bash)