name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Get
      run: go get -v
      
    - name: Build
      run: go build -v ./...

    - name: Copy
      run: |
        mv files/test/go go.mod
        mv files/test/jsql/jsql_test jsql/jsql_test.go
        sed -i 's/MYSQL_DSN/${{ secrets.MYSQL_DSN }}/g' files/test-jconf.json
        sed -i 's/MYSQL_DB/${{ secrets.MYSQL_DB }}/g' files/test-jconf.json
        sed -i 's/MSSQL_DSN/${{ secrets.MSSQL_DSN }}/g' files/test-jconf.json
        sed -i 's/MSSQL_DB/${{ secrets.MSSQL_DB }}/g' files/test-jconf.json
        sed -i 's/ORACLE_DSN/${{ secrets.ORACLE_DSN }}/g' files/test-jconf.json
        sed -i 's/ORACLE_DB/${{ secrets.ORACLE_DB }}/g' files/test-jconf.json
        sed -i 's/POSTGRESQL_DSN/${{ secrets.POSTGRESQL_DSN }}/g' files/test-jconf.json
        sed -i 's/POSTGRESQL_DB/${{ secrets.POSTGRESQL_DB }}/g' files/test-jconf.json

    - name: Get
      run: go get -v

    - name: Test
      run: go test -v ./... -covermode=count -coverprofile=coverage.out

    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)
