package jsql

const (
	sqlQueryTablesMySql  = `SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = ? ORDER BY TABLE_NAME`
	sqlQueryTablesMSSql  = `SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES ORDER BY TABLE_NAME`
	sqlQueryTablesOracle = `SELECT OBJECT_NAME AS TABLE_NAME FROM USER_OBJECTS WHERE OBJECT_TYPE IN ('TABLE', 'VIEW') ORDER BY TABLE_NAME`

	sqlQueryTableSchemaMySql = `SELECT
									C.COLUMN_NAME,
									C.DATA_TYPE,
									C.IS_NULLABLE,
									C.COLUMN_DEFAULT,
									KCU.ORDINAL_POSITION AS PRIMARY_KEY,
									C.COLUMN_COMMENT,
									T.TABLE_COMMENT

								FROM INFORMATION_SCHEMA.COLUMNS AS C

								LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS KCU
									ON C.TABLE_CATALOG = KCU.TABLE_CATALOG
									AND C.TABLE_SCHEMA = KCU.TABLE_SCHEMA
									AND C.TABLE_NAME = KCU.TABLE_NAME
									AND C.COLUMN_NAME = KCU.COLUMN_NAME

								LEFT JOIN INFORMATION_SCHEMA.TABLES AS T
									ON C.TABLE_CATALOG = T.TABLE_CATALOG
									AND C.TABLE_SCHEMA = T.TABLE_SCHEMA
									AND C.TABLE_NAME = T.TABLE_NAME

								WHERE
									C.TABLE_SCHEMA = ?
									AND C.TABLE_NAME = ?

								ORDER BY C.ORDINAL_POSITION`
	sqlQueryTableSchemaMSSql = `SELECT
									C.COLUMN_NAME,
									C.DATA_TYPE,
									C.IS_NULLABLE,
									C.COLUMN_DEFAULT,
									KCU.ORDINAL_POSITION AS PRIMARY_KEY,
									SEPCD.VALUE AS COLUMN_COMMENT,
									SEPTD.VALUE AS TABLE_COMMENT

								FROM INFORMATION_SCHEMA.COLUMNS AS C

								LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS KCU
									ON C.TABLE_CATALOG = KCU.TABLE_CATALOG
									AND C.TABLE_SCHEMA = KCU.TABLE_SCHEMA
									AND C.TABLE_NAME = KCU.TABLE_NAME
									AND C.COLUMN_NAME = KCU.COLUMN_NAME

								LEFT JOIN SYSOBJECTS AS S
									ON C.TABLE_NAME = S.NAME

								LEFT JOIN SYS.TABLES ST
									ON S.ID = ST.OBJECT_ID
									AND ST.SCHEMA_ID = SCHEMA_ID(C.TABLE_SCHEMA)

								LEFT JOIN SYS.COLUMNS SC
									on S.ID = SC.OBJECT_ID
									AND C.COLUMN_NAME = SC.NAME

								LEFT JOIN SYS.EXTENDED_PROPERTIES SEPCD
									ON S.ID = SEPCD.MAJOR_ID
									AND SEPCD.NAME = 'MS_Description'
									AND SC.COLUMN_ID = SEPCD.MINOR_ID

								LEFT JOIN SYS.EXTENDED_PROPERTIES SEPTD
									ON S.ID = SEPTD.MAJOR_ID
									AND SEPTD.NAME = 'MS_Description'
									AND SEPTD.MINOR_ID = 0

								WHERE C.TABLE_NAME = ?

								ORDER BY C.ORDINAL_POSITION`
	sqlQueryTableSchemaOracle = `SELECT
									ATC.COLUMN_NAME,
									ATC.DATA_TYPE,
									CASE WHEN ATC.NULLABLE = 'Y' THEN 'YES' ELSE 'NO' END AS IS_NULLABLE,
									ATC.DATA_DEFAULT,
									ACC.POSITION AS PRIMARY_KEY,
									ACCM.COMMENTS AS COLUMN_COMMENT,
									ATCM.COMMENTS AS TABLE_COMMENT

								FROM ALL_TAB_COLUMNS ATC

								LEFT JOIN ALL_CONSTRAINTS AC
									ON ATC.OWNER = AC.OWNER
									AND ATC.TABLE_NAME = AC.TABLE_NAME
									AND AC.CONSTRAINT_TYPE = 'P'

								LEFT JOIN ALL_CONS_COLUMNS ACC
									ON ATC.OWNER = ACC.OWNER
									AND ATC.TABLE_NAME = ACC.TABLE_NAME
									AND ATC.COLUMN_NAME = ACC.COLUMN_NAME
									AND AC.CONSTRAINT_NAME = ACC.CONSTRAINT_NAME

								LEFT JOIN ALL_COL_COMMENTS ACCM
									ON ATC.OWNER = ACCM.OWNER
									AND ATC.TABLE_NAME = ACCM.TABLE_NAME
									AND ATC.COLUMN_NAME = ACCM.COLUMN_NAME

								LEFT JOIN ALL_TAB_COMMENTS ATCM
									ON ATC.OWNER = ATCM.OWNER
									AND ATC.TABLE_NAME = ATCM.TABLE_NAME

								WHERE
									ATC.OWNER = ?
									AND ATC.TABLE_NAME = ?

								ORDER BY ATC.COLUMN_ID`
)
