package jsql

const (
	sqlQueryTablesMySql      = `SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = ? ORDER BY TABLE_NAME`
	sqlQueryTablesMSSql      = `SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES ORDER BY TABLE_NAME`
	sqlQueryTablesOracle     = `SELECT OBJECT_NAME AS TABLE_NAME FROM USER_OBJECTS WHERE OBJECT_TYPE IN ('TABLE', 'VIEW') ORDER BY TABLE_NAME`
	sqlQueryTablesPostgreSql = `SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'public' ORDER BY TABLE_NAME`

	sqlQueryTableSchemaMySql = `SELECT
    								DISTINCT
									C.COLUMN_NAME,
									C.DATA_TYPE,
									C.IS_NULLABLE,
									C.COLUMN_DEFAULT AS DATA_DEFAULT,
									KCU.ORDINAL_POSITION AS PRIMARY_KEY,
									CASE WHEN C.EXTRA LIKE '%auto_increment%' THEN 'YES' ELSE 'NO' END AS IS_IDENTITY,
									C.COLUMN_COMMENT,
									T.TABLE_COMMENT,
									C.ORDINAL_POSITION

								FROM INFORMATION_SCHEMA.COLUMNS AS C

								LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS KCU
									ON C.TABLE_CATALOG = KCU.TABLE_CATALOG
									AND C.TABLE_SCHEMA = KCU.TABLE_SCHEMA
									AND C.TABLE_NAME = KCU.TABLE_NAME
									AND C.COLUMN_NAME = KCU.COLUMN_NAME

								LEFT JOIN INFORMATION_SCHEMA.TABLES AS T
									ON C.TABLE_CATALOG = T.TABLE_CATALOG
									AND C.TABLE_SCHEMA = T.TABLE_SCHEMA
									AND C.TABLE_NAME = T.TABLE_NAME

								WHERE
									C.TABLE_SCHEMA = ?
									AND C.TABLE_NAME = ?

								ORDER BY C.ORDINAL_POSITION`
	sqlQueryTableSchemaMSSql = `SELECT
    								DISTINCT
									C.COLUMN_NAME,
									C.DATA_TYPE,
									C.IS_NULLABLE,
									C.COLUMN_DEFAULT AS DATA_DEFAULT,
									KCU.ORDINAL_POSITION AS PRIMARY_KEY,
									CASE WHEN SC.IS_IDENTITY = 'true' THEN 'YES' ELSE 'NO' END AS IS_IDENTITY,
									SEPCD.VALUE AS COLUMN_COMMENT,
									SEPTD.VALUE AS TABLE_COMMENT,
									C.ORDINAL_POSITION

								FROM INFORMATION_SCHEMA.COLUMNS AS C

								LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS KCU
									ON C.TABLE_CATALOG = KCU.TABLE_CATALOG
									AND C.TABLE_SCHEMA = KCU.TABLE_SCHEMA
									AND C.TABLE_NAME = KCU.TABLE_NAME
									AND C.COLUMN_NAME = KCU.COLUMN_NAME

								LEFT JOIN SYSOBJECTS AS S
									ON C.TABLE_NAME = S.NAME

								LEFT JOIN SYS.TABLES ST
									ON S.ID = ST.OBJECT_ID
									AND ST.SCHEMA_ID = SCHEMA_ID(C.TABLE_SCHEMA)

								LEFT JOIN SYS.COLUMNS SC
									on S.ID = SC.OBJECT_ID
									AND C.COLUMN_NAME = SC.NAME

								LEFT JOIN SYS.EXTENDED_PROPERTIES SEPCD
									ON S.ID = SEPCD.MAJOR_ID
									AND SEPCD.NAME = 'MS_Description'
									AND SC.COLUMN_ID = SEPCD.MINOR_ID

								LEFT JOIN SYS.EXTENDED_PROPERTIES SEPTD
									ON S.ID = SEPTD.MAJOR_ID
									AND SEPTD.NAME = 'MS_Description'
									AND SEPTD.MINOR_ID = 0

								WHERE C.TABLE_NAME = @p1

								ORDER BY C.ORDINAL_POSITION`
	sqlQueryTableSchemaOracle = `WITH
    								FUNCTION GET_DEF(O IN VARCHAR2, T IN VARCHAR2, C IN VARCHAR2) RETURN VARCHAR2 IS VAL VARCHAR2(4000);
        								BEGIN
            								SELECT ATC.DATA_DEFAULT INTO VAL
                                    			FROM   ALL_TAB_COLUMNS ATC
                                    			WHERE  ATC.OWNER = O
                                      				AND ATC.TABLE_NAME = T
                                      				AND ATC.COLUMN_NAME = C;
            								RETURN VAL;
        								END;
									SELECT
										DISTINCT
									ATC.COLUMN_NAME,
									ATC.DATA_TYPE,
									CASE WHEN ATC.NULLABLE = 'Y' THEN 'YES' ELSE 'NO' END AS IS_NULLABLE,
    								CASE WHEN
        								GET_DEF(ATC.OWNER, ATC.TABLE_NAME, ATC.COLUMN_NAME) = 'null'
            							OR GET_DEF(ATC.OWNER, ATC.TABLE_NAME, ATC.COLUMN_NAME) LIKE CONCAT(CONCAT('%"', ATC.OWNER), '"."ISEQ$$_%')
        								THEN NULL
    								    ELSE GET_DEF(ATC.OWNER, ATC.TABLE_NAME, ATC.COLUMN_NAME) END AS DATA_DEFAULT,
									ACC.POSITION AS PRIMARY_KEY,
									CASE WHEN GET_DEF(ATC.OWNER, ATC.TABLE_NAME, ATC.COLUMN_NAME) LIKE CONCAT(CONCAT('%"', ATC.OWNER), '"."ISEQ$$_%')
									    THEN 'YES'
									    ELSE 'NO' END AS IS_IDENTITY,
									ACCM.COMMENTS AS COLUMN_COMMENT,
									ATCM.COMMENTS AS TABLE_COMMENT,
									ATC.COLUMN_ID

								FROM ALL_TAB_COLUMNS ATC

								LEFT JOIN ALL_CONSTRAINTS AC
									ON ATC.OWNER = AC.OWNER
									AND ATC.TABLE_NAME = AC.TABLE_NAME
									AND AC.CONSTRAINT_TYPE = 'P'

								LEFT JOIN ALL_CONS_COLUMNS ACC
									ON ATC.OWNER = ACC.OWNER
									AND ATC.TABLE_NAME = ACC.TABLE_NAME
									AND ATC.COLUMN_NAME = ACC.COLUMN_NAME
									AND AC.CONSTRAINT_NAME = ACC.CONSTRAINT_NAME

								LEFT JOIN ALL_COL_COMMENTS ACCM
									ON ATC.OWNER = ACCM.OWNER
									AND ATC.TABLE_NAME = ACCM.TABLE_NAME
									AND ATC.COLUMN_NAME = ACCM.COLUMN_NAME

								LEFT JOIN ALL_TAB_COMMENTS ATCM
									ON ATC.OWNER = ATCM.OWNER
									AND ATC.TABLE_NAME = ATCM.TABLE_NAME

								WHERE
									ATC.OWNER = :0
									AND ATC.TABLE_NAME = :1

								ORDER BY ATC.COLUMN_ID`

	sqlQueryTableSchemaPostgreSql = `SELECT
    								DISTINCT
									CAST(C.COLUMN_NAME AS VARCHAR) AS COLUMN_NAME,
									C.DATA_TYPE,
									C.IS_NULLABLE,
									C.COLUMN_DEFAULT AS DATA_DEFAULT,
									KCU.ORDINAL_POSITION AS PRIMARY_KEY,
									C.IS_IDENTITY,
									PD.DESCRIPTION AS COLUMN_COMMENT,
									OBJ_DESCRIPTION(PC.OID) AS TABLE_COMMENT,
									C.ORDINAL_POSITION

								FROM INFORMATION_SCHEMA.COLUMNS AS C

								LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS KCU
									ON C.TABLE_CATALOG = KCU.TABLE_CATALOG
									AND C.TABLE_SCHEMA = KCU.TABLE_SCHEMA
									AND C.TABLE_NAME = KCU.TABLE_NAME
									AND C.COLUMN_NAME = KCU.COLUMN_NAME

								LEFT JOIN INFORMATION_SCHEMA.TABLES AS T
									ON C.TABLE_CATALOG = T.TABLE_CATALOG
									AND C.TABLE_SCHEMA = T.TABLE_SCHEMA
									AND C.TABLE_NAME = T.TABLE_NAME
								    
								LEFT JOIN PG_CLASS AS PC
									ON C.TABLE_NAME = PC.RELNAME

								LEFT JOIN PG_DESCRIPTION AS PD
								    ON PC.OID = PD.OBJOID
								    AND C.ORDINAL_POSITION = PD.OBJSUBID

								WHERE
									C.TABLE_SCHEMA = 'public'
									AND C.TABLE_NAME = $1

								ORDER BY C.ORDINAL_POSITION`
)
